import type { Locale } from './i18n';

const en = [
  'Plan a 2-week Italy road trip',
  'Weekend drive through the Alps',
  'Barcelona to Amsterdam in 10 days',
  'Coastal road trip along the Amalfi Coast',
  'Road trip through the Scottish Highlands',
  'Berlin to Prague weekend getaway',
  'Drive the Ring of Kerry in Ireland',
  'French Riviera road trip from Nice to Monaco',
  'Explore the Basque Country by car',
  'Nordic road trip: Oslo to Tromsø',
  'Portugal from Lisbon to Porto in a week',
  'Drive the Romantic Road in Germany',
  'Greek island-hopping road trip through the Peloponnese',
  'Road trip through the Dolomites',
  'Budapest to Dubrovnik along the coast',
  'Andalusia road trip: Seville, Granada, Málaga',
  'Drive through Tuscany with vineyard stops',
  'Swiss Alps road trip: Zurich to Geneva',
  'Baltic road trip: Tallinn, Riga, Vilnius',
  'Road trip through Provence lavender fields',
  'Explore the Norwegian fjords by car',
  'Drive from Paris to the Loire Valley castles',
  'Road trip through the Croatian coastline',
  'Iceland Ring Road in 10 days',
  'Drive from Munich to Venice through the Alps',
  'Explore Transylvania by car',
  'Road trip along the Atlantic coast of France',
  'Drive through the Cotswolds in England',
  'Scandinavian capitals road trip',
  'Explore the Cinque Terre coast by car',
  'Road trip from Amsterdam to Copenhagen',
  'Drive the Wild Atlantic Way in Ireland',
  'Austrian Alps: Salzburg to Innsbruck',
  'Road trip through southern France wine regions',
  'Explore Sardinia by car in one week',
  'Drive from Rome to Sicily',
  'Road trip through the Balkans',
  'Explore the Black Forest in Germany',
  'Drive from Lisbon to the Algarve',
  'Polish road trip: Warsaw, Krakow, Gdansk',
  'Road trip through the Pyrenees',
  'Explore the Lofoten Islands by car',
  'Drive from Vienna to the Dalmatian Coast',
  'Road trip along the Rhine Valley',
  'Explore Cornwall and Devon by car',
  'Drive from Stockholm to Gothenburg coast road',
  'Road trip through northern Spain',
  'Explore the Lake District in England',
  'Drive from Brussels to Luxembourg wine country',
  'Road trip through the Périgord and Dordogne',
  'Explore Corsica by car',
  'Drive along the Adriatic coast of Italy',
  'Road trip from Helsinki to Lapland',
  'Explore the Mosel Valley by car',
  'Drive through Slovenia: Ljubljana to Bled',
  'Road trip around Mont Blanc',
  'Explore the Alentejo region of Portugal',
  'Drive from Edinburgh to the Isle of Skye',
  'Road trip through Champagne and Burgundy',
  'Explore the Azores by car',
  'Drive from Copenhagen to the Swedish west coast',
  'Road trip through the Italian Lakes',
  'Explore Crete by car in one week',
  'Drive the E75 from Finland to Greece',
  'Road trip through Flanders: Bruges, Ghent, Antwerp',
  'Explore the Danube Bend from Budapest',
  'Drive from Zurich to Lake Como',
  'Road trip through the Welsh countryside',
  'Explore Montenegro by car',
  'Drive from Madrid to San Sebastián',
  'Road trip through the Austrian wine country',
  'Explore the Faroe Islands by car',
  'Drive from Naples to the Puglia coast',
  'Road trip through the Bohemian countryside',
  'Explore the Swedish archipelago by car',
];

const sv = [
  'Planera en 2-veckors roadtrip i Italien',
  'Helgresa genom Alperna',
  'Barcelona till Amsterdam på 10 dagar',
  'Kustresa längs Amalfikusten',
  'Roadtrip genom skotska höglandet',
  'Berlin till Prag på en helg',
  'Kör Ring of Kerry på Irland',
  'Franska Rivieran från Nice till Monaco',
  'Utforska Baskien med bil',
  'Nordisk roadtrip: Oslo till Tromsø',
  'Portugal från Lissabon till Porto på en vecka',
  'Kör Romantiska vägen i Tyskland',
  'Grekisk roadtrip genom Peloponnesos',
  'Roadtrip genom Dolomiterna',
  'Budapest till Dubrovnik längs kusten',
  'Andalusien: Sevilla, Granada, Málaga',
  'Kör genom Toscana med vingårdsstopp',
  'Schweiziska Alperna: Zürich till Genève',
  'Baltisk roadtrip: Tallinn, Riga, Vilnius',
  'Roadtrip genom Provences lavendelfält',
  'Utforska norska fjordarna med bil',
  'Paris till Loires slottsdal',
  'Roadtrip längs Kroatiens kust',
  'Islands ringväg på 10 dagar',
  'München till Venedig genom Alperna',
  'Utforska Transsylvanien med bil',
  'Roadtrip längs Frankrikes atlantkust',
  'Kör genom Cotswolds i England',
  'Skandinaviska huvudstäder roadtrip',
  'Utforska Cinque Terre-kusten med bil',
  'Amsterdam till Köpenhamn med bil',
  'Kör Wild Atlantic Way på Irland',
  'Österrikiska Alperna: Salzburg till Innsbruck',
  'Roadtrip genom södra Frankrikes vinregioner',
  'Utforska Sardinien med bil på en vecka',
  'Kör från Rom till Sicilien',
  'Roadtrip genom Balkan',
  'Utforska Schwarzwald i Tyskland',
  'Kör från Lissabon till Algarve',
  'Polsk roadtrip: Warszawa, Krakow, Gdansk',
  'Roadtrip genom Pyrenéerna',
  'Utforska Lofoten med bil',
  'Kör från Wien till Dalmatiens kust',
  'Roadtrip längs Rhendalen',
  'Utforska Cornwall och Devon med bil',
  'Kör från Stockholm till Göteborg kustvägem',
  'Roadtrip genom norra Spanien',
  'Utforska Engelska sjödistriktet',
  'Bryssel till Luxemburgs vinland',
  'Roadtrip genom Périgord och Dordogne',
  'Utforska Korsika med bil',
  'Kör längs Italiens adriatiska kust',
  'Helsingfors till Lappland med bil',
  'Utforska Moseldalen med bil',
  'Kör genom Slovenien: Ljubljana till Bled',
  'Roadtrip runt Mont Blanc',
  'Utforska Alentejo i Portugal',
  'Kör från Edinburgh till Isle of Skye',
  'Roadtrip genom Champagne och Bourgogne',
  'Utforska Azorerna med bil',
  'Köpenhamn till svenska västkusten',
  'Roadtrip genom de italienska sjöarna',
  'Utforska Kreta med bil på en vecka',
  'Kör E75 från Finland till Grekland',
  'Roadtrip genom Flandern: Brugge, Gent, Antwerpen',
  'Utforska Donaukröken från Budapest',
  'Kör från Zürich till Comosjön',
  'Roadtrip genom walesiska landsbygden',
  'Utforska Montenegro med bil',
  'Kör från Madrid till San Sebastián',
  'Roadtrip genom österrikiskt vinland',
  'Utforska Färöarna med bil',
  'Kör från Neapel till Apuliens kust',
  'Roadtrip genom böhmiska landsbygden',
  'Utforska svenska skärgården med bil',
];

const suggestions: Record<Locale, string[]> = { en, sv };

export function getRandomSuggestions(locale: Locale, count = 3): string[] {
  const pool = suggestions[locale];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
